### ISSUE TITLE
@alch/alchemy-web3 ^1.3.0 version issue 

### ISSUE THREAD

**Issue by Kcin1993** [alchemyplatform/hello-world-part-four-tutorial#3]
Here is my package.json config. 

```
{
  "name": "hello-world-part-four",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@alch/alchemy-web3": "^1.3.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "dotenv": "^16.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

It will show this error on react client. 

<img width="1512" alt="截圖 2022-04-07 下午6 07 03" src="https://user-images.githubusercontent.com/8435927/162176815-4884a92c-99e7-4937-8c52-1ecb7a286b05.png">

If I change  `"@alch/alchemy-web3": "^1.3.0",` into `"@alch/alchemy-web3": "1.1.5",` it works fine.

**Comment by thebrianchen** [comment]
@Kcin1993 What are you passing as the url when you call `createAlchemyWeb3()`?

This seems similar to https://github.com/alchemyplatform/alchemy-web3/issues/117

**Comment by Kcin1993** [comment]
@thebrianchen Thanks for your reply!
I found the reason is I didn't move `.env` into starter-files thus causing the `REACT_APP_ALCHEMY_KEY` couldn't be read

**Comment by jsina** [comment]
does the `alchemy-web3` package deprecate?
if yes, how can we replace it with `alchemy-sdk`?
